-- Schema for the five report entities. The system has exactly one device (the ESP32, id 1) and
-- three sensors; they are required data and are created here, not by the development seeds.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT,
    email      TEXT        NOT NULL UNIQUE,
    password   TEXT        NOT NULL, -- bcrypt hash
    username   TEXT        NOT NULL UNIQUE,
    phone      TEXT,
    avatar     TEXT,
    github     TEXT,
    figma      TEXT,
    role       TEXT        NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE devices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    type       TEXT        NOT NULL,
    status     TEXT        NOT NULL DEFAULT 'OFF' CHECK (status IN ('ON', 'OFF')),
    mqtt_topic TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sensors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    type       TEXT        NOT NULL UNIQUE CHECK (type IN ('temperature', 'humidity', 'light')),
    unit       TEXT        NOT NULL,
    status     TEXT,
    mqtt_topic TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sensor_data (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id BIGINT           NOT NULL REFERENCES sensors (id),
    value     DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMPTZ      NOT NULL DEFAULT now()
);

CREATE INDEX sensor_data_sensor_id_idx ON sensor_data (sensor_id);
CREATE INDEX sensor_data_timestamp_idx ON sensor_data (timestamp DESC);
CREATE INDEX sensor_data_sensor_id_timestamp_idx ON sensor_data (sensor_id, timestamp DESC);

CREATE TABLE device_actions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users (id) ON DELETE SET NULL,
    device_id    BIGINT      NOT NULL REFERENCES devices (id),
    action       TEXT        NOT NULL CHECK (action IN ('TURN_ON', 'TURN_OFF')),
    result       TEXT        NOT NULL CHECK (result IN ('PENDING', 'SUCCESS', 'FAILED', 'TIMEOUT')),
    message      TEXT,
    timestamp    TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX device_actions_timestamp_idx ON device_actions (timestamp DESC);
CREATE INDEX device_actions_device_id_timestamp_idx ON device_actions (device_id, timestamp DESC);

INSERT INTO devices (id, name, type, status, mqtt_topic)
VALUES (1, 'ESP32', 'LED', 'OFF', 'myiot/esp32/device-control');

INSERT INTO sensors (id, name, type, unit, mqtt_topic)
VALUES (1, 'Temperature', 'temperature', '°C', 'myiot/esp32/sensor-data'),
       (2, 'Humidity', 'humidity', '%', 'myiot/esp32/sensor-data'),
       (3, 'Light', 'light', 'lux', 'myiot/esp32/sensor-data');

-- Keep the identity sequences past the explicit ids.
SELECT setval(pg_get_serial_sequence('devices', 'id'), (SELECT max(id) FROM devices));
SELECT setval(pg_get_serial_sequence('sensors', 'id'), (SELECT max(id) FROM sensors));
